In [1]:
import numpy as np
import matplotlib.pyplot as plt

n = 6
k = 10

def zeidel (B,c,n,k,x0):
    result=np.zeros([k,n])
    y=np.array(x0)
    for m in range(k):
        x=np.array(y)
        for i in range(n):
            u=0
            j=0
            while (j>=0) and (j<=i):
                u+=B[i,j]*y[j]
                j+=1
            j=i+1
            while (j>=i) and (j<n):
                u+=B[i,j]*x[j]
                j+=1
            y[i]=u+c[i]
        for i in range(n):
                result[m,i]=y[i]
    return result


In [2]:
def B2(B):
    res = np.zeros([B.shape[0], B.shape[1]])
    for i in range (B.shape[0]):
        for j in range(i+1, B.shape[0]):
            res[i,j] = B[i,j]
    return(res)

In [3]:
def zeidel_modified(B, c, n, x0, eps):
    y=np.array(x0)
    x=np.zeros(n)
    k=0
    
    new_eps=((1-np.linalg.norm(B, np.inf))*eps/np.linalg.norm(B2(B), np.inf))
    while (max(abs(x-y)) > new_eps):
        x=np.array(y)
        k+=1
        for i in range(n):
            u=0
            j=0
            while (j>=0) and (j<=i):
                u+=B[i,j]*y[j]
                j+=1
            j=i+1
            while (j>=i) and (j<n):
                u+=B[i,j]*x[j]
                j+=1
            y[i]=u+c[i]
    return y, k

In [25]:
A = np.array([[3.96,-1.5,0,-0.99,-1.4,0],
              [3.96,18.3,1.6,6.93,4.3,1.5],
              [0,4.6,-13,4.29,-1.4,2.3],
              [3.96,0.4,0,5.94,1.5,0],
              [5.94,3.1,3.4,0.99,14.4,0.9],
              [-2.97,-1.2,0.8,4.95,-2.7,12.7]])
b = np.array([11.95,-64.89,-38.57,-23.82,-84.83,30.35])

In [26]:
x = np.linalg.solve(A,b)
x.reshape(n,1)

array([[-0.26262626],
       [-1.6       ],
       [ 2.6       ],
       [-2.21212121],
       [-6.        ],
       [ 1.6       ]])

In [29]:
B = np.zeros([n,n])
c = np.zeros(n)

for i in range(A.shape[0]):
    c[i]=b[i]/A[i,i]
    for j in range(A.shape[1]):
        if i!=j:
            B[i,j]=-A[i,j]/A[i,i]
B
            

array([[ 0.        ,  0.37878788, -0.        ,  0.25      ,  0.35353535,
        -0.        ],
       [-0.21639344,  0.        , -0.08743169, -0.37868852, -0.23497268,
        -0.08196721],
       [ 0.        ,  0.35384615,  0.        ,  0.33      , -0.10769231,
         0.17692308],
       [-0.66666667, -0.06734007, -0.        ,  0.        , -0.25252525,
        -0.        ],
       [-0.4125    , -0.21527778, -0.23611111, -0.06875   ,  0.        ,
        -0.0625    ],
       [ 0.23385827,  0.09448819, -0.06299213, -0.38976378,  0.21259843,
         0.        ]])

In [30]:
np.linalg.norm(B, np.inf)

0.9994535519125683

In [31]:
x1 = np.zeros(n)
z1 = zeidel(B,c,n,k,x1)
z1

array([[ 3.01767677e+00, -4.19890710e+00,  1.48115595e+00,
        -5.73913083e+00, -6.18698463e+00,  3.52698629e+00],
       [-2.19491885e+00,  1.37582531e-01,  2.41198887e+00,
        -9.93716734e-01, -5.73680265e+00,  9.05207058e-01],
       [ 7.93199628e-01, -2.27832541e+00,  2.61078141e+00,
        -2.93679064e+00, -6.19879982e+00,  2.02232610e+00],
       [-7.71017827e-01, -1.20441041e+00,  2.59696539e+00,
        -1.84963056e+00, -5.92605024e+00,  1.39311401e+00],
       [ 3.98479960e-03, -1.79511692e+00,  2.60601382e+00,
        -2.39539692e+00, -6.04386208e+00,  1.70564336e+00],
       [-3.97859908e-01, -1.50021062e+00,  2.59824346e+00,
        -2.11760899e+00, -5.97838424e+00,  1.54567209e+00],
       [-1.93557266e-01, -1.65120920e+00,  2.60112914e+00,
        -2.26017730e+00, -6.01103401e+00,  1.62762727e+00],
       [-2.97938623e-01, -1.57393091e+00,  2.59944212e+00,
        -2.18754877e+00, -5.99433009e+00,  1.58586824e+00],
       [-2.44603980e-01, -1.61333036e+00,  2.600

In [32]:
max(abs(z1[k-1]-x)) #погрешность

0.00920652982907555

In [41]:
x2 = np.array([15.1,23.5,2.2,14.3,41,1.1])
z2 = zeidel(B,c,n,k,x2)
z2

array([[ 29.98914141, -25.36699454,  -5.5108596 , -32.64818219,
         -9.32355513,  18.09613758],
       [-18.04928519,  13.9126518 ,   1.32166079,   9.44030999,
         -3.53281555,  -5.03044566],
       [  9.39872293,  -8.02776901,   2.73208532,  -8.84320065,
         -7.76244796,   5.45357872],
       [ -4.97824478,   2.01825418,   2.5636382 ,   1.1330336 ,
         -5.29597972,  -0.31276016],
       [  2.19310932,  -3.40363955,   2.65146119,  -3.90560396,
         -6.40088352,   2.57546082],
       [ -1.51092025,  -0.67883335,   2.58285557,  -1.34072343,
         -5.80021235,   1.09903071],
       [  0.37478194,  -2.07230191,   2.61029043,  -2.6557066 ,
         -6.10187739,   1.85502255],
       [ -0.58844211,  -1.35937969,   2.59485018,  -1.98538742,
         -5.9477121 ,   1.46960915],
       [ -0.09631314,  -1.72299875,   2.60259936,  -2.3279179 ,
         -6.02662855,   1.6665802 ],
       [ -0.34758001,  -1.53719337,   2.59865824,  -2.1529904 ,
         -5.98638715,   1.5

In [43]:
max(abs(z2[k-1]-x))

0.08495374343728379

In [59]:
x3 = np.array([50., 1234., -113., 5345., -8., 6.])
z3 = zeidel_modified(B,c,n,x3,10**(-6))
print ("Корни системы для приближения", z3[0])
print ("Итераций всего:", z3[1])

Корни системы для приближения [-0.26262626 -1.6         2.6        -2.21212121 -6.          1.6       ]
Итераций всего: 46


In [60]:
max(abs(z3[0]-x))

1.748738931439675e-10